version: 0.1

phases:
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Compiling the Ruby code..."
      - ruby helloworld.rb 
  post_build:
    commands:
      - echo Build completed on `date`
